sudo: false
language: php
php:
  - 5.5
  - 5.6
  - hhvm
services:
  - memcached
before_script:
  - composer self-update
  - chmod -R 755 tests/bin/memcached.sh
  - tests/bin/memcached.sh
script:
  - composer install
  - vendor/bin/phpunit -c app/phpunit.xml