sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
services:
  - memcached
before_install:
  - composer self-update
install:
  - composer --prefer-source --dev install
before_script:
  - chmod -R 755 tests/bin/memcached.sh
  - tests/bin/memcached.sh
script:
  - vendor/bin/phpspec run
  - vendor/bin/phpunit -c app/phpunit.xml